version: '3.4'

services:
  api:
    build: ./
    ports:
      - '5002:5002'
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5002
      #- ASPNETCORE_URLS=https://+:5001;http://+:5000
      #- ASPNETCORE_HTTPS_PORT=5001
      #- ASPNETCORE_Kestrel__Certificates__Default__Password=mypassword123
      #- ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    #volumes:
    #  - ./webapi/https/aspnetapp.pfx:/https/aspnetapp.pfx:ro
    restart: always
    networks:
      - coords_net

networks:
  coords_net:
    name: coords_net
    external: true
  
    
    
#    networks:
#      - coords_net
#networks:
#  coords_net:
#    external: true

